name = "webrtc-video-chat-workers"
main = "src/index.ts"
compatibility_date = "2026-05-19"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "Room" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
